"""Configuration constants for the Directory server."""

DEFAULT_HOST = "0.0.0.0"
DEFAULT_PORT = 5000

ALIVE_TIMEOUT_SECONDS = 3.0
CLIENT_LIST_INTERVAL_SECONDS = 1.0
BUFFER_SIZE = 4096

DIRECTORY_SENDER = "directory"
